eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

microservice:
  user-service:
    endpoints:
      endpoint:
        uri: http://user-service/user/userById/
  hotel-service:
    endpoints:
      endpoint:
        uri: http://hotel-service/hotel/recipeById/

